#!/usr/bin/env bash
# script that installs and sets up nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' >/var/www/html/index.html
service nginx start
