#!/usr/bin/env bash
# script that configures nginx server to redirect /redirect_me to another page

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" >/etc/nginx/sites-available/default
service nginx restart
