#!/usr/bin/env bash
# script that configures nginx server to have a custom 404 page that contains
# the string "Ceci n'est pas une page"

apt-get update
apt-get install -y nginx

echo "Ceci n'est pas une page" >/var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" >/etc/nginx/sites-available/default

service nginx restart
