#!/usr/bin/env bash
# script that installs and configures HAproxy

apt-get update -y
apt-get install -y haproxy
printf %s "global
	log /dev/log    local0
	log /dev/log    local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 530937-web-01 52.87.235.175:80 check
	server 530937-web-02 100.25.192.241:80 check
" >>/etc/haproxy/haproxy.cfg
echo "ENABLED=1" >>/etc/default/haproxy
service haproxy start
