#!/usr/bin/env bash
# script that loops from 1 to 10
# displays bad luck for 4th loop iteration
# displays good luck for 8th loop iteration
# displays Best School for other iterations

i=0
while ((i < 10)); do
	if ((i == 3)); then
		echo "bad luck"
	elif ((i == 7)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
